sharedDir: ".config"
outputDir: "lib"

mergeRules:
  ".gitignore": true
  ".husky/commit-msg": true
  ".npmignore": true

ignorePatterns:
  ".gitignore": [
    ".env",
    "/.husky/",
    "node_modules/",
  ]
  ".npmignore": [
    ".config",
    ".env",
    ".gitattributes",
    ".github",
    ".husky",
    "node_modules/",
  ]

executableFiles: [
  ".husky/commit-msg",
]

scripts:
  "generate": "npm-run-all generate:*"
  "generate:changelog": "changelog generate --bump"
  "prepare:config": "k8s-manifest-shared-config"
  "prepare:husky": "husky install"
  "release": "npm-run-all prepare lint generate"

dependencies:
  - '@tagproject/docs-shared-config': '1.x'
  - '@tagproject/vscode-shared-config': '2.x'
  - "changelog-guru"
  - "husky": "8.x"











